dataset_splits:
  - dataset_id: "custom"
    split: "steered_top10_dynamic_momentum_silu"
    prompt_column: "prompt"

model:
  name_or_path: "/mnt/bignvme/ai-stack/ai-backends/models/huggingface/google/gemma-4-E2B-it"
  max_model_len: 4096
  max_new_tokens: 512
  num_return_sequences: 1
  temperature: 0.0
  batch_size: 64

judge_model:
  name_or_path: "/mnt/bignvme/ai-stack/ai-backends/models/huggingface/google/gemma-4-E2B-it"
  max_model_len: 8192
  max_new_tokens: 256
  num_return_sequences: 1
  temperature: 0.0
  batch_size: 64

continue_from_checkpoint: true
enforce_eager: true
gpu_memory_utilization: 0.90
tensor_parallel_size: "auto"
parallel_dataset_load: true

output_dir: "results/gemma-4-E2B-it"
